import RestaurantNavBar from '../components/RestaurantNavBar';
import Menu from './components/Menu';
import { PrismaClient } from '@prisma/client';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Menu',
  description: 'Generated by create next app',
};

const prisma = new PrismaClient();

const fetchItems = async (slug: string) => {
  const restaurant = await prisma.restaurant.findUnique({
    where: {
      slug,
    },
    select: {
      Item: true,
    },
  });

  if (!restaurant) {
    throw new Error('Restaurant not found');
  }

  return restaurant.Item;
};

const RestaurantMenu = async ({ params }: { params: { slug: string } }) => {
  const items = await fetchItems(params.slug);

  return (
    <>
      <div className="bg-white w-[100%] rounded p-3 shadow">
        <RestaurantNavBar slug={params.slug} />
        <Menu items={items} />
      </div>
    </>
  );
};

export default RestaurantMenu;
