import React from 'react';
import Header from './components/Header';
import SearchSideBar from './components/SearchSideBar';
import RestaurantCard from './components/RestaurantCard';
import type { Metadata } from 'next';
import { PRICE, PrismaClient } from '@prisma/client';

export const metadata: Metadata = {
  title: 'Search',
  description: 'Generated by create next app',
};

const prisma = new PrismaClient();

export interface SearchParamsType {
  cuisine?: string;
  city?: string;
  price?: PRICE;
}

const fetchRestaurantsByParams = (searchParams: SearchParamsType) => {
  const where: any = {};

  if (searchParams.city) {
    where.location = {
      name: {
        equals: searchParams.city.toLowerCase(),
      },
    };
  }

  if (searchParams.cuisine) {
    where.cuisine = {
      name: {
        equals: searchParams.cuisine.toLowerCase(),
      },
    };
  }

  if (searchParams.price) {
    where.price = {
      equals: searchParams.price,
    };
  }

  return prisma.restaurant.findMany({
    where,
    select: {
      id: true,
      name: true,
      main_image: true,
      price: true,
      location: true,
      cuisine: true,
      slug: true,
      reviews: true,
    },
  });
};

const fetchLocations = () => {
  return prisma.location.findMany();
};

const fetchCuisines = () => {
  return prisma.cuisine.findMany();
};

const SearchPage = async ({ searchParams }: { searchParams: SearchParamsType }) => {
  const restaurants = await fetchRestaurantsByParams(searchParams);
  const locations = await fetchLocations();
  const cuisines = await fetchCuisines();

  return (
    <>
      <Header />
      <div className="flex py-4 m-auto w-2/3 justify-between items-start">
        <SearchSideBar locations={locations} cuisines={cuisines} searchParams={searchParams} />
        <div className="w-5/6">
          {restaurants.length === 0 ? (
            <p>Sorry, we found no restaurants</p>
          ) : (
            restaurants.map((restaurant) => (
              <RestaurantCard key={restaurant.id} restaurant={restaurant} />
            ))
          )}
        </div>
      </div>
    </>
  );
};

export default SearchPage;
