import Header from './components/Header';
import Form from './components/Form';

import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Reserve',
  description: 'Generated by create next app',
  icons: {
    icon: [{ url: 'https://static-00.iconduck.com/assets.00/next-js-icon-2048x2048-5dqjgeku.png' }],
  },
};


const ReservationPage = () => {
  return (
    <>
      <div className="border-t h-screen">
        <div className="py-9 w-3/5 m-auto">
          <Header />
          <Form />
        </div>
      </div>
    </>
  );
};

export default ReservationPage;
